apiVersion: v1
kind: Secret
metadata:
  name: db-secret-credentials
  namespace: gitlab
  labels:
    app: postgresdb
type: Opaque
stringData:
  POSTGRES_DB: gitlabhq_production
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
