apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster-bonus
servers: 1
agents: 1
ports:
  - port: 8888:30080
    nodeFilters:
      - loadbalancer
  - port: 8081:8081
    nodeFilters:
      - loadbalancer
files:
  - source: ./k8s/argocd/argocd-app.yaml
    destination: /var/lib/rancher/k3s/server/manifests/argocd/argocd-app.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/argocd/argocd-helmchart.yaml
    destination: /var/lib/rancher/k3s/server/manifests/argocd/argocd-helmchart.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/argocd/argocd-namespace.yaml
    destination: /var/lib/rancher/k3s/server/manifests/argocd/argocd-namespace.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/argocd/argocd-service.yaml
    destination: /var/lib/rancher/k3s/server/manifests/argocd/argocd-service.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/gitlab/gitlab-namespace.yaml
    destination: /var/lib/rancher/k3s/server/manifests/gitlab/gitlab-namespace.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/postgres/db-configmap.yaml
    destination: /var/lib/rancher/k3s/server/manifests/postgres/db-configmap.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/postgres/db-deployment.yaml
    destination: /var/lib/rancher/k3s/server/manifests/postgres/db-deployment.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/postgres/db-persistent-volume.yaml
    destination: /var/lib/rancher/k3s/server/manifests/postgres/db-persistent-volume.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/postgres/db-service.yaml
    destination: /var/lib/rancher/k3s/server/manifests/postgres/db-service.yaml
    nodeFilters:
      - "server:*"
  - source: ./k8s/postgres/db-volume-claim.yaml
    destination: /var/lib/rancher/k3s/server/manifests/postgres/db-volume-claim.yaml
    nodeFilters:
      - "server:*"
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - "server:*"
