apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: ClusterIP
  selector:
    app: jellyfin
  ports:
    - name: udp
      port: 7359
      targetPort: 7359
    - name: tcp
      port: 80
      targetPort: 8096


