# -*- mode: ruby -*-
# vi: set ft=ruby :

K3S_TOKEN = "4242TokenIOTicham"

SERVER_IP  = "192.168.56.110"
WORKER_IP  = "192.168.56.111"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  config.vm.define "ijaberS", primary: true do |server|
    server.vm.hostname = "ijaberS"
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider :virtualbox do |vb|
      vb.cpus   = 1
      vb.memory = 1024
      vb.linked_clone = true
    end

    server.vm.provision "shell", path: "scripts/script.sh", args: ["server", SERVER_IP, K3S_TOKEN]
  end

  config.vm.define "ijaberSW" do |worker|
    worker.vm.hostname = "ijaberSW"
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider :virtualbox do |vb|
      vb.cpus   = 1
      vb.memory = 1024
      vb.linked_clone = true
    end

    # Appel du script externe pour l'agent
    worker.vm.provision "shell", path: "scripts/script.sh", args: ["agent", SERVER_IP, K3S_TOKEN]
  end

end
