# -*- mode: ruby -*-
# vi: set ft=ruby :

# Token partagé entre le Server et l'Agent pour rejoindre le cluster K3s.
K3S_TOKEN = "4242TokenIOTicham"

#IPs
SERVER_IP  = "192.168.122.110"
WORKER_IP  = "192.168.122.111"

Vagrant.configure("2") do |config|

  # debian/bookworm64 = Debian 12
  config.vm.box = "generic/debian12"

  # Désactive la vérification de mise à jour de la box à chaque `vagrant up`
  config.vm.box_check_update = false

  # Machine 1 : ijaberS (Server / Controller K3s)
  config.vm.define "ijaberS" do |server|

    server.vm.hostname = "ijaberS"

    server.vm.network "private_network",
      ip: SERVER_IP

    # Provider par défaut : libvirt
    config.vm.provider :libvirt do |lv|
      lv.cpus   = 1
      lv.memory = 1024
      #lv.qemu_use_session = true
    end

    server.vm.provision "shell", inline: <<-SHELL
      set -e  # Arrête le script à la première erreur

      echo ">>> [ijaberS] Installation de K3s en mode server..."

      # --flannel-iface eth1 : K3s doit utiliser l'interface host-only (eth1),
      # pas l'interface NAT Vagrant (eth0) pour la communication inter-nœuds.
      # --write-kubeconfig-mode 644 : rend kubeconfig lisible par l'user vagrant.
      curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="server \
          --flannel-iface eth1 \
          --write-kubeconfig-mode 644" \
        K3S_TOKEN="#{K3S_TOKEN}" \
        sh -

      echo ">>> [ijaberS] K3s server démarré."

      # Attendre que le nœud soit Ready avant de continuer
      # (utile si le worker provisionne juste après)
      echo ">>> [ijaberS] Attente que le nœud soit Ready..."
      until kubectl get nodes 2>/dev/null | grep -q "Ready"; do
        sleep 3
      done

      echo ">>> [ijaberS] Nœud prêt !"
    SHELL
  end

  # Machine 2 : ijaberSW (ServerWorker / Agent K3s)
  config.vm.define "ijaberSW" do |worker|

    worker.vm.hostname = "ijaberSW"

    worker.vm.network "private_network",
      ip: WORKER_IP

    worker.vm.provider "libvirt" do |lv|
      lv.cpus   = 1
      lv.memory = 1024
      #lv.qemu_use_session = true
    end

    worker.vm.provision "shell", inline: <<-SHELL
      set -e

      echo ">>> [ijaberSW] Installation de K3s en mode agent..."

      # K3S_URL : adresse du server auquel l'agent doit se connecter.
      # K3S_TOKEN : même token que le server → authentification mutuelle.
      curl -sfL https://get.k3s.io | \
        K3S_URL="https://#{SERVER_IP}:6443" \
        K3S_TOKEN="#{K3S_TOKEN}" \
        sh -

      echo ">>> [ijaberSW] Agent K3s démarré et connecté à ijaberS."
    SHELL
  end

end
