apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: "*"
    helm:
      values: |
        architecture: standalone
        auth:
          existingSecret: redis-auth
          existingSecretPasswordKey: redis-password
        master:
          persistence:
            size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
