apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/iot.git
    targetRevision: main
    path: bonus/confs/k8s/app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
