apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minio-secret
  namespace: gitlab
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    aws_access_key_id: agruet
    aws_secret_access_key: passwd123456
    aws_signature_version: 4
    host: minio.gitlab.svc.cluster.local
    endpoint: "http://minio.gitlab.svc.cluster.local:9000"
    path_style: true
