# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/trixie64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # /!\ NECESSAIRE SUR VM DANS UNE VM (question d'instructions processeur)
  config.vm.provider 'libvirt' do |libvirt|
    libvirt.memory = 2048
  end

  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.hostname = "bzaidiS"

  config.vm.provision "file",
    source: "../",
    destination: "/home/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    yes | apt install curl
    echo ">>> [bzaidiS] Installation de k3s"
    curl -sfL https://get.k3s.io | sh -
    echo ">>> [bzaidiS] Lancement des pods"
    cd /home/vagrant/scripts
    sh start.sh
  SHELL
end
